# Generated by Django 5.0.3 on 2024-03-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viand',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viandtype',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
